Bump to v1.0.3, fix istanbul-lib-coverage import
After updating mbland/tomcat-servlet-testing-example to use v1.0.2, its
tests failed with this error:

```text
FAIL  main.test.js [ main.test.js ]
SyntaxError: Named export 'createCoverageMap' not found. The requested module
'istanbul-lib-coverage' is a CommonJS module, which may not support all
module.exports as named exports.

CommonJS modules can always be imported via the default export, for example
using:

import pkg from 'istanbul-lib-coverage';
const { createCoverageMap } = pkg;
```

At least it was a very clear and straightforward message leading to an easy
fix. Still, gah.