Bump to v1.0.2, add .js extension to local imports
After installing v1.0.1 in a local copy of
mbland/tomcat-servlet-testing-example, running the tests against jsdom
broke with:

```text
  FAIL  main.test.js [ main.test.js ]
  Error: Cannot find module
  '.../tomcat-servlet-testing-example/strcalc/src/main/frontend/node_modules/.pnpm/test-page-opener@1.0.1/node_modules/test-page-opener/lib/browser'
  imported from
  .../tomcat-servlet-testing-example/strcalc/src/main/frontend/node_modules/.pnpm/test-page-opener@1.0.1/node_modules/test-page-opener/index.js
  ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
  Serialized Error: {
    code: 'ERR_MODULE_NOT_FOUND',
    url: 'file:///.../tomcat-servlet-testing-example/strcalc/src/main/frontend/node_modules/.pnpm/test-page-opener@1.0.1/node_modules/test-page-opener/lib/browser'
  }
```

Running `pnpm link ../../../../../test-page-opener` and running the
tests again worked, so I wouldn't've caught this before releasing
v1.0.1, either.

And apparently this is quite a thing, especially impacting TypeScript
users:

- https://www.google.com/search?q=node+import+requires+.js+extension
- https://github.com/nodejs/node/issues/46006
- https://nodejs.org/docs/latest-v18.x/api/esm.html#import-specifiers

So be it.